// массив с координатами и цветами
const state = [
  {
    color: '#6abf4b',
    show: false,
    colorLight: '#6abf4ba2',
    text: 'Стадион',
    x: '44',
    y: '35',
  },
  {
    color: '#3878ee',
    show: false,
    colorLight: '#3878eea2',
    text: 'Мэрия',
    x: '66',
    y: '83',
  },
  {
    color: '#6abf4b',
    show: false,
    colorLight: '#6abf4ba2',
    text: 'Дом 5',
    x: '37',
    y: '60',
  },
  {
    color: '#3878ee',
    show: false,
    colorLight: '#3878eea2',
    text: 'Вокзал',
    x: '44',
    y: '74',
  },
  {
    color: '#3878ee',
    show: false,
    colorLight: '#3878eea2',
    text: 'Администрация стадиона',
    x: '58',
    y: '56',
  },
  {
    color: '#3878ee',
    show: false,
    colorLight: '#3878eea2',
    text: 'Дом 2',
    x: '20',
    y: '72',
  },
  {
    color: '#6abf4b',
    show: false,
    colorLight: '#6abf4ba2',
    text: 'отель мир',
    x: '62',
    y: '68',
  },
  {
    color: '#6abf4b',
    show: false,
    colorLight: '#6abf4ba2',
    text: 'отель мираж',
    x: '73',
    y: '57',
  },
  {
    color: '#3878ee',
    show: false,
    colorLight: '#3878eea2',
    text: 'Дом 8',
    x: '26',
    y: '30',
  },
  {
    color: '#3878ee',
    show: false,
    colorLight: '#3878eea2',
    text: 'Мост',
    x: '66',
    y: '23',
  },
];
